export const textStyles = {
    h1: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: [
            'xxLarge',
            null,
            'superLarge',
        ],
        lineHeight: [
            'xxLarge',
            null,
            'superLarge',
        ],
        marginTop: [
            11,
            null,
            18,
        ],
        marginBottom: [
            4,
            null,
            6,
        ],
    },
    h2: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: [
            'xLargePlus',
            null,
            'xxxLarge',
        ],
        lineHeight: [
            'xLargePlus',
            null,
            'xxxLarge',
        ],
        marginTop: [
            10,
            null,
            16,
        ],
        marginBottom: [
            4,
            null,
            6,
        ],
    },
    h3: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: [
            'xLarge',
            null,
            'xxLargePlus',
        ],
        lineHeight: [
            'xLarge',
            null,
            'xxLargePlus',
        ],
        marginTop: [
            8,
            null,
            14,
        ],
        marginBottom: [
            4,
            null,
            4,
        ],
    },
    h4: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: [
            'largePlus',
            null,
            'xLargePlus',
        ],
        lineHeight: [
            'largePlus',
            null,
            'xLargePlus',
        ],
        marginTop: [
            8,
            null,
            10,
        ],
        marginBottom: [
            4,
            null,
            4,
        ],
    },
    h5: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: [
            'large',
            null,
            'largePlus',
        ],
        lineHeight: [
            'large',
            null,
            'largePlus',
        ],
        marginTop: 8,
        marginBottom: 4,
    },
    h6: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: 'base',
        lineHeight: 'base',
        marginTop: 8,
        marginBottom: 4,
    },
    p1: {
        fontFamily: 'body',
        fontWeight: 'normal',
        fontSize: 'base',
        lineHeight: 'base',
        marginTop: 6,
        marginBottom: 4,
    },
    p2: {
        fontFamily: 'body',
        fontWeight: 'normal',
        fontSize: 'small',
        lineHeight: 'small',
        marginTop: 5,
        marginBottom: 3,
    },
    p3: {
        fontFamily: 'body',
        fontWeight: 'normal',
        fontSize: 'smallPlus',
        lineHeight: 'smallPlus',
        marginTop: 4,
        marginBottom: 3,
    },
    p4: {
        fontFamily: 'body',
        fontWeight: 'normal',
        fontSize: 'mini',
        lineHeight: 'mini',
        marginTop: 3,
        marginBottom: 2,
    },
    btn: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: 'small',
        lineHeight: 'base',
        marginTop: 0,
        marginBottom: 0,
    },
    lead: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: [
            'xxLargePlus',
            null,
            'mega',
        ],
        lineHeight: [
            'xxLargePlus',
            null,
            'mega',
        ],
        marginTop: [
            14,
            null,
            20,
        ],
        marginBottom: [
            4,
            null,
            6,
        ],
    },
};
