import {
    any,
    array,
    boolean,
    integer,
    number,
    object,
    optional,
    pattern,
    string,
    type,
    union,
} from 'superstruct';


export const BaseTypes = object({
    // Specific Attributes
    children: any(),
    dangerouslySetInnerHTML: optional(object({
        __html: string(),
    })),

    // Global HTML Attributes
    accessKey: optional(string()),
    className: optional(string()),
    contentEditable: optional(union([boolean(), pattern(string(), /inherit/)])),
    contextMenu: optional(string()),
    // data-*: ...,
    dir: optional(union([pattern(string(), /ltr/), pattern(string(), /rtl/)])),
    draggable: optional(union([boolean(), pattern(string(), /auto/)])),
    dropzone: optional(union([pattern(string(), /copy/), pattern(string(), /link/), pattern(string(), /move/)])),
    hidden: optional(boolean()),
    id: optional(string()),
    lang: optional(string()),
    spellCheck: optional(boolean()),
    style: optional(type({})),
    tabIndex: optional(integer()),
    title: optional(string()),
    translate: optional(union([pattern(string(), /yes/), pattern(string(), /no/)])),
});

export const HTMLTypes = object({
    // Standard HTML Attributes
    accept: optional(string()),
    acceptCharset: optional(string()),
    action: optional(string()),
    allowFullScreen: optional(boolean()),
    allowTransparency: optional(boolean()),
    alt: optional(string()),
    as: optional(string()),
    async: optional(boolean()),
    autoComplete: optional(string()),
    autoFocus: optional(boolean()),
    autoPlay: optional(boolean()),
    capture: optional(union([boolean(), pattern(string(), /environment/), pattern(string(), /user/)])),
    cellPadding: optional(union([number(), string()])),
    cellSpacing: optional(union([number(), string()])),
    charSet: optional(string()),
    challenge: optional(string()),
    checked: optional(boolean()),
    cite: optional(string()),
    classID: optional(string()),
    cols: optional(number()),
    colSpan: optional(number()),
    content: optional(string()),
    controls: optional(boolean()),
    coords: optional(string()),
    crossOrigin: optional(string()),
    data: optional(string()),
    dateTime: optional(string()),
    default: optional(boolean()),
    defer: optional(boolean()),
    disabled: optional(boolean()),
    download: optional(any()),
    encType: optional(string()),
    form: optional(string()),
    formAction: optional(string()),
    formEncType: optional(string()),
    formMethod: optional(string()),
    formNoValidate: optional(boolean()),
    formTarget: optional(string()),
    frameBorder: optional(union([number(), string()])),
    headers: optional(string()),
    height: optional(union([number(), string()])),
    high: optional(number()),
    href: optional(string()),
    hrefLang: optional(string()),
    htmlFor: optional(string()),
    httpEquiv: optional(string()),
    integrity: optional(string()),
    keyParams: optional(string()),
    keyType: optional(string()),
    kind: optional(string()),
    label: optional(string()),
    list: optional(string()),
    loop: optional(boolean()),
    low: optional(number()),
    manifest: optional(string()),
    marginHeight: optional(number()),
    marginWidth: optional(number()),
    max: optional(union([number(), string()])),
    maxLength: optional(number()),
    media: optional(string()),
    mediaGroup: optional(string()),
    method: optional(string()),
    min: optional(union([number(), string()])),
    minLength: optional(number()),
    multiple: optional(boolean()),
    muted: optional(boolean()),
    name: optional(string()),
    nonce: optional(string()),
    noValidate: optional(boolean()),
    open: optional(boolean()),
    optimum: optional(number()),
    pattern: optional(string()),
    placeholder: optional(string()),
    playsInline: optional(boolean()),
    poster: optional(string()),
    preload: optional(string()),
    readOnly: optional(boolean()),
    rel: optional(string()),
    required: optional(boolean()),
    reversed: optional(boolean()),
    rows: optional(number()),
    rowSpan: optional(number()),
    sandbox: optional(string()),
    scope: optional(string()),
    scoped: optional(boolean()),
    scrolling: optional(string()),
    seamless: optional(boolean()),
    selected: optional(boolean()),
    shape: optional(string()),
    size: optional(number()),
    sizes: optional(string()),
    span: optional(number()),
    src: optional(string()),
    srcDoc: optional(string()),
    srcLang: optional(string()),
    srcSet: optional(string()),
    start: optional(number()),
    step: optional(union([number(), string()])),
    summary: optional(string()),
    target: optional(string()),
    type: optional(string()),
    useMap: optional(string()),
    value: optional(union([string(), array(union([number(), string()]))])),
    width: optional(union([number(), string()])),
    wmode: optional(string()),
    wrap: optional(string()),
});
